apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-datastore
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.datastore.service.type }}
  ports:
    - name: http
      port: {{ .Values.datastore.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: datastore
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-datastore
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: datastore
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-datastore
  replicas: {{ .Values.datastore.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: datastore
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: datastore
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: volume-gid-ds
          image: busybox
          command:
            - sh
            - -c
            - chown -R 185:0 /home/data
          volumeMounts:
            - name: pvc-{{ include "chatbot.fullname" . }}-datastore
              mountPath: /home/data
      containers:
        - name: datastore-container
          image: io2060/2060-datastore:main
          imagePullPolicy: {{ .Values.datastore.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.datastore.service.port }}
          resources:
            {{- toYaml .Values.datastore.resources | nindent 12 }}
          env:
            {{- range .Values.datastore.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
          volumeMounts:
            - name: datastore-data
              mountPath: /home/data
      volumes:
        - name: datastore-data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.datastore.storage.pvcName . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.datastore.storage.pvcName . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "chatbot.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: {{ .Values.datastore.storage.storageClassName | default "csi-cinder-classic" }}
  resources:
    requests:
      storage: {{ .Values.datastore.storage.size | default "1Gi" }}
