apiVersion: v1
kind: Secret
metadata:
  name: faucet-app-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.faucetApp.secret }}
  {{- range $key, $val := .Values.faucetApp.secret }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-faucet-app
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.faucetApp.service.type }}
  ports:
    - name: http
      port: {{ .Values.faucetApp.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: faucet-app
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-faucet-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: faucet-app
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-faucet-app
  replicas: {{ .Values.faucetApp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: faucet-app
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: faucet-app
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: faucet-app-container
          image: veranalabs/faucet-app:latest
          imagePullPolicy: {{ .Values.faucetApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.faucetApp.service.port }}
          resources:
            {{- toYaml .Values.faucetApp.resources | nindent 12 }}
          env:
            {{- range .Values.faucetApp.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
            {{- range $key, $val := .Values.faucetApp.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: faucet-app-secret
                  key: {{ $key }}
            {{- end }}
