{{- if .Values.postgres.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ tpl .Values.postgres.secret.password $ | quote }}
---
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    {{- include "chatbot.selectorLabels" . | nindent 4 }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "postgres:15.2"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          env:
            {{- range .Values.postgres.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.postgres.storage.pvcName . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.postgres.storage.pvcName . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "chatbot.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: {{ .Values.postgres.storage.storageClassName | default "csi-cinder-classic" }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | default "1Gi" }}
