apiVersion: v1
kind: Secret
metadata:
  name: stats-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.stats.secret }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-stats
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.stats.service.type }}
  ports:
    - name: http
      port: {{ .Values.stats.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: stats
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatbot.fullname" . }}-stats
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ tpl .Values.stats.ingress.host $ }}
      secretName: {{ tpl .Values.stats.ingress.tlsSecret $ }}
  rules:
    - host: {{ tpl .Values.stats.ingress.host $ }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot.fullname" . }}-stats
                port:
                  number: {{ .Values.stats.service.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-stats
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: stats
    {{ include "chatbot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chatbot.fullname" . }}-stats
  replicas: {{ .Values.stats.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: stats
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: stats
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: stats-container
          image: mobiera/stats:v1.1.5
          imagePullPolicy: {{ .Values.stats.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.stats.service.port }}
          resources:
            {{- toYaml .Values.stats.resources | nindent 12 }}
          env:
            {{- range .Values.stats.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
            {{- range $key, $val := .Values.stats.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: stats-secret
                  key: {{ $key }}
            {{- end }}