apiVersion: v2
name: verana-faucet-hologram-chatbot-chart
version: 1.3.2
appVersion: '1.3.2'
description: Helm chart to deploy verana-faucet-hologram-chatbot
dependencies:
  - name: vs-agent-chart
    version: v1.7.0
    repository: oci://registry-1.docker.io/veranalabs
    condition: vs-agent-chart.enabled
